### ISSUE TITLE
Request to check if it is possible to build the new features of C++20 on MacOS

### ISSUE THREAD

**Issue by habu1010** [backwardsEric/hengband#33]
I am currently working on a Pull Request for hengband in the following branch, which uses the C++20 ranges library feature.

https://github.com/habu1010/hengband/tree/feature/implement-rand-choice-function

According to [this page](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features), I think the ranges library feature is supported in Xcode 14.3/Apple Clang 14.0.3. Could you please check if this branch can be built on MacOS?

**Comment by backwardsEric** [comment]
The machine I use is too old to upgrade to macOS 13 so I'm stuck at macOS 12.6.5 and Xcode 14.2 with clang 14.0.0.  As expected from the page you linked, compilation of your branch fails on that machine:

```
depbase=`echo action/action-limited.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	./gcc-wrap g++ -std=gnu++20 -DHAVE_CONFIG_H -I. -I../src     -include ../src/stdafx.h  -g -O2 -MT action/action-limited.o -MD -MP -MF $depbase.Tpo -c -o action/action-limited.o action/action-limited.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from action/action-limited.cpp:8:
In file included from ./game-option/disturbance-options.h:3:
In file included from ./system/angband.h:21:
./term/z-rand.h:115:27: error: no member named 'borrowed_range' in namespace 'std::ranges'
    requires std::ranges::borrowed_range<T> && std::ranges::sized_range<T>
             ~~~~~~~~~~~~~^
In file included from action/action-limited.cpp:8:
In file included from ./game-option/disturbance-options.h:3:
In file included from ./system/angband.h:22:
./term/z-term.h:89:21: error: use of undeclared identifier 'term_win'
    std::unique_ptr<term_win> old; //!< Displayed screen image
                    ^
./term/z-term.h:90:21: error: use of undeclared identifier 'term_win'
    std::unique_ptr<term_win> scr; //!< Requested screen image
                    ^
./term/z-term.h:92:21: error: use of undeclared identifier 'term_win'
    std::unique_ptr<term_win> tmp; //!< Temporary screen image
                    ^
./term/z-term.h:93:32: error: use of undeclared identifier 'term_win'
    std::stack<std::unique_ptr<term_win>> mem_stack; //!< Memorized screen image stack
                               ^
./term/z-term.h:193:20: error: unknown type name 'term_win'
errr term_win_nuke(term_win *s, TERM_LEN w, TERM_LEN h);
                   ^
6 errors generated.
make[2]: *** [action/action-limited.o] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

On GitHub, Xcode 14.3 is available, but isn't the default, on the macos-13 runner.  I haven't gotten a workflow up and running on that yet (problems with autoconf and m4) but will try some more and see if it compiles.

**Comment by habu1010** [comment]
Thank you for confirming.
Unfortunately, I will try to implement this without using the ranges library feature until Xcode 14.3 and later become a more common environment.
I will not use it at this time, but if you can somehow find out if it is possible to compile with Xcode 14.3, I would appreciate it if you could continue to check.

**Comment by backwardsEric** [comment]
It did compile and link with Xcode 14.3.  The workflow result is here, https://github.com/backwardsEric/hengband/actions/runs/4996152896 .  There doesn't appear to be any additional runtime requirement to support the C++ ranges so the generated executable should run on at least macOS 10.15 and later.

In my hands, there was trouble with the bootstrap script in that environment (eventually I skipped it and the configure script entirely), but that's a separate problem, likely due to the old version of m4 (1.4.6) that's included with macOS.

**Comment by habu1010** [comment]
Thank you for providing the additional information.
Once we are in a position to compile and distribute the application in your environment, we would consider using the features of the C++20 ranges library.
I will close this Issue.
